# Now You Code In Class: Tricks of The Pandas Masters

We will try something a bit different in the Activity - A series of Pandas coding challenges!


For this Now You Code, you will need the Zomato api https://developers.zomato.com/api which provides API access to local area restaurants information.


In [1]:
import pandas as pd
import import_ipynb
import googleapi as google
import requests

pd.set_option('display.max_colwidth', None)
google_api_key = '751838d6b9978955679461c80a7df60bde4f093d'

importing Jupyter notebook from googleapi.ipynb


## Warm-Up 1

Load the following data set into a data frame, called `exam_df`

https://raw.githubusercontent.com/mafudge/datasets/master/exam-scores/exam-scores.csv

HINT: observe the file format!

In [7]:
exams = pd.read_csv(
    "https://raw.githubusercontent.com/mafudge/datasets/master/exam-scores/exam-scores.csv")

# SHOW ME LETTER GRADES OF STUDENTS WHO MADE THEIR OWN STUDY GUIDE
# show the columns
exams.columns

made_study = exams[ 
    exams['Made_Own_Study_Guide'] =='Y'
]
letter_grades = made_study[
    ['Made_Own_Study_Guide','Letter_Grade']
]
letter_grades

Made_Own_Study_Guide Letter_Grade
2                     Y            A
4                     Y            B
6                     Y            A
7                     Y           B+
9                     Y           A-
12                    Y            A
13                    Y           B+
14                    Y           B+
16                    Y           C+
18                    Y           A-
19                    Y           B-
25                    Y            C
26                    Y           C-
27                    Y           C+
34                    Y            B
36                    Y            B
38                    Y           B-
42                    Y           A-
44                    Y            B
45                    Y           A-
46                    Y            D
48                    Y           A-
52                    Y            D
57                    Y           C+
61                    Y           C+
63                    Y            B

## Warm-Up 2

Load the following HTML table into a data frame called `res_df`

https://en.wikipedia.org/wiki/Graphics_display_resolution#High-definition

HINT: Which table is it on the page?

In [14]:
page = pd.read_html("https://en.wikipedia.org/wiki/Graphics_display_resolution#High-definition")
res_df = page[4]
res_df

Name  H (px)  V (px)   H:V  H × V (Mpx)
0      nHD     640     360  16:9        0.230
1      qHD     960     540  16:9        0.518
2       HD    1280     720  16:9        0.922
3      HD+    1600     900  16:9        1.440
4      FHD    1920    1080  16:9        2.074
5   (W)QHD    2560    1440  16:9        3.686
6     QHD+    3200    1800  16:9        5.760
7   4K UHD    3840    2160  16:9        8.294
8       5K    5120    2880  16:9       14.746
9   8K UHD    7680    4320  16:9       33.178
10     16K   15360    8640  16:9      132.710

## Warm-Up 3

For your `exam_df` display exams where the students made their own study guide  and finished in 30 minutes or less.

HINT: This can be multiple steps


## Warm-Up 4

For your `res_df`, display the displays which are larger than 1920 x 1080. Show columns `Name` and `H:V` only

HINT: Again, think multiple steps

In [18]:
a = res_df[
    res_df["H (px)"] > 1920
]
b = a[
    a["V (px)"] > 1080
]
c = b[
    ["Name", "H:V"]
]
from IPython.display import display
display(a)
display(c)

Name  H (px)  V (px)   H:V  H × V (Mpx)
5   (W)QHD    2560    1440  16:9        3.686
6     QHD+    3200    1800  16:9        5.760
7   4K UHD    3840    2160  16:9        8.294
8       5K    5120    2880  16:9       14.746
9   8K UHD    7680    4320  16:9       33.178
10     16K   15360    8640  16:9      132.710

Name   H:V
5   (W)QHD  16:9
6     QHD+  16:9
7   4K UHD  16:9
8       5K  16:9
9   8K UHD  16:9
10     16K  16:9

## Challenge 1

1. Search the Open Street Maps  geocode api for "Syracuse" (leave off the NY) put the results in a dataframe (there should be several results). 

Example:
https://nominatim.openstreetmap.org/search?q=Syracuse&format=json


In [19]:
response = requests.get("https://nominatim.openstreetmap.org/search?q=Syracuse&format=json")
data = response.json()
data

[{'place_id': 332268789,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 174916,
  'boundingbox': ['42.984165', '43.086121', '-76.204629', '-76.074273'],
  'lat': '43.0481221',
  'lon': '-76.1474244',
  'display_name': 'City of Syracuse, Onondaga County, New York, United States',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.6767762857760726,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons/poi_boundary_administrative.p.20.png'},
 {'place_id': 17360479,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 1932675079,
  'boundingbox': ['36.9046139', '37.2246139', '15.1307196', '15.4507196'],
  'lat': '37.0646139',
  'lon': '15.2907196',
  'display_name': 'Siracusa, Sicilia, Italia',
  'class': 'place',
  'type': 'city',
  'importance': 0.5980544326919952,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicon

## Challenge 2

1. Load the locations into a dataframe. using the `pd.DataFrame()` method. Start with whatever is of type `list` as that will automatically place it into a `DataFrame` 

In [20]:
df = pd.DataFrame(data)
df

place_id  \
0  332268789   
1   17360479   
2  282155297   
3     314722   
4  282399933   
5  282297678   
6  337438257   
7     272085   
8  282327320   
9   67315254   

                                                                  licence  \
0  Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright   
1  Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright   
2  Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright   
3  Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright   
4  Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright   
5  Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright   
6  Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright   
7  Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright   
8  Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright   
9  Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright   

   osm_type      osm_id                                           boundingbox  \
0  relation      174916        [42.984165, 43.086121, -76.204629, -76.074273]   
1      node  1932675079      [36.9046139, 37.2246139, 15.1307196, 15.4507196]   
2  relation       39169      [36.9477054, 37.1156703, 15.0829726, 15.3367251]   
3      node   151698827    [37.9405686, 38.0205686, -101.792671, -101.712671]   
4  relation      129906      [37.941272, 37.990492, -101.816776, -101.736708]   
5  relation      169314        [40.651206, 40.672865, -96.197821, -96.172004]   
6       way  1053073126       [42.984165, 43.086102, -76.2046186, -76.074273]   
7      node   150932996  [41.0495938, 41.1295938, -112.1038903, -112.0238903]   
8  relation      198737     [41.0529648, 41.11093, -112.1159667, -112.035662]   
9      node  6241108067    [43.0718312, 43.0818312, -76.1744003, -76.1644003]   

           lat                  lon  \
0   43.0481221          -76.1474244   
1   37.0646139           15.2907196   
2   37.0315712     15.2124310355363   
3   37.9805686          -101.752671   
4     37.95317  -101.79804971938925   
5    40.657224           -96.186398   
6   43.0355579   -76.14099681510547   
7   41.0895938         -112.0638903   
8  41.08175315  -112.05978386426273   
9   43.0768312          -76.1694003   

                                                                                                   display_name  \
0                                                    City of Syracuse, Onondaga County, New York, United States   
1                                                                                     Siracusa, Sicilia, Italia   
2                                                                                     Siracusa, Sicilia, Italia   
3                                                       Syracuse, Hamilton County, Kansas, 67878, United States   
4                                                       Syracuse, Hamilton County, Kansas, 67878, United States   
5                                                                Syracuse, Otoe County, Nebraska, United States   
6                                                            Syracuse, Onondaga County, New York, United States   
7                                                            Syracuse, Davis County, Utah, 84075, United States   
8                                                            Syracuse, Davis County, Utah, 84075, United States   
9  Syracuse, 131, NBT Bank Parkway, City of Syracuse, Syracuse, Onondaga County, New York, 13208, United States   

      class            type  importance  \
0  boundary  administrative    0.676776   
1     place            city    0.598054   
2  boundary  administrative    0.598054   
3     place            town    0.535495   
4  boundary  administrative    0.535495   
5  boundary  administrative    0.461126   
6     place            city    0.460000   
7     place            town    0.436855   
8  b

## Challenge 3

1. Let's call the IST256 google places search api, looking for bars in the Syracuse NY area, and load the results into a dataframe. You can call `google.googlePlacesSearch()` With these inputs lat=`43.0481`, lng=`-76.1474`, type=`'bar'`



In [23]:
import json
data = google.googlePlacesSearch(google_api_key=google_api_key,lat=43.0481, lng=-76.1474, place_type='food')
df = pd.DataFrame(data)
df

geometry  \
0        {'location': {'lat': 43.0481221, 'lng': -76.14742439999999}, 'viewport': {'northeast': {'lat': 43.0861018469036, 'lng': -76.07408408072611}, 'southwest': {'lat': 42.98436599077808, 'lng': -76.20447601435613}}}   
1                  {'location': {'lat': 43.0476078, 'lng': -76.1417642}, 'viewport': {'northeast': {'lat': 43.0489864302915, 'lng': -76.1406058697085}, 'southwest': {'lat': 43.0462884697085, 'lng': -76.1433038302915}}}   
2                   {'location': {'lat': 43.0476157, 'lng': -76.140986}, 'viewport': {'northeast': {'lat': 43.0488486802915, 'lng': -76.1396400197085}, 'southwest': {'lat': 43.0461507197085, 'lng': -76.1423379802915}}}   
3          {'location': {'lat': 43.0472894, 'lng': -76.15385049999999}, 'viewport': {'northeast': {'lat': 43.0486011802915, 'lng': -76.1525313197085}, 'southwest': {'lat': 43.0459032197085, 'lng': -76.15522928029151}}}   
4                {'location': {'lat': 43.0488846, 'lng': -76.1561175}, 'viewport': {'northeast': {'lat': 43.0501538302915, 'lng': -76.15480331970849}, 'southwest': {'lat': 43.0474558697085, 'lng': -76.15750128029151}}}   
5    {'location': {'lat': 43.05264399999999, 'lng': -76.14681999999999}, 'viewport': {'northeast': {'lat': 43.0542440802915, 'lng': -76.1455149697085}, 'southwest': {'lat': 43.0515461197085, 'lng': -76.1482129302915}}}   
6          {'location': {'lat': 43.0526411, 'lng': -76.15469379999999}, 'viewport': {'northeast': {'lat': 43.0539544302915, 'lng': -76.15343391970849}, 'southwest': {'lat': 43.0512564697085, 'lng': -76.1561318802915}}}   
7          {'location': {'lat': 43.0464172, 'lng': -76.13539879999999}, 'viewport': {'northeast': {'lat': 43.0478319802915, 'lng': -76.13413491970849}, 'southwest': {'lat': 43.0451340197085, 'lng': -76.1368328802915}}}   
8                  {'location': {'lat': 43.0446639, 'lng': -76.1481366}, 'viewport': {'northeast': {'lat': 43.0460742302915, 'lng': -76.1464777697085}, 'southwest': {'lat': 43.0433762697085, 'lng': -76.1491757302915}}}   
9                {'location': {'lat': 43.0457297, 'lng': -76.1483396}, 'viewport': {'northeast': {'lat': 43.0470192302915, 'lng': -76.14723521970849}, 'southwest': {'lat': 43.0443212697085, 'lng': -76.14993318029151}}}   
10               {'location': {'lat': 43.048302, 'lng': -76.155406}, 'viewport': {'northeast': {'lat': 43.04965963029149, 'lng': -76.15412261970849}, 'southwest': {'lat': 43.04696166970849, 'lng': -76.15682058029151}}}   
11  {'location': {'lat': 43.04396249999999, 'lng': -76.13607999999999}, 'viewport': {'northeast': {'lat': 43.0451998802915, 'lng': -76.13499536970849}, 'southwest': {'lat': 43.0425019197085, 'lng': -76.1376933302915}}}   
12                  {'location': {'lat': 43.050228, 'lng': -76.154804}, 'viewport': {'northeast': {'lat': 43.0514909802915, 'lng': -76.15379486970849}, 'southwest': {'lat': 43.0487930197085, 'lng': -76.1564928302915}}}   
13       {'location': {'lat': 43.04737250000001, 'lng': -76.1525762}, 'viewport': {'northeast': {'lat': 43.04875913029151, 'lng': -76.1510592697085}, 'southwest': {'lat': 43.04606116970851, 'lng': -76.15375723029152}}}   
14                 {'location': {'lat': 43.0437854, 'lng': -76.141393}, 'viewport': {'northeast': {'lat': 43.0449497802915, 'lng': -76.14004761970848}, 'southwest': {'lat': 43.0422518197085, 'lng': -76.1427455802915}}}   
15                 {'location': {'lat': 43.042709, 'lng': -76.140511}, 'viewport': {'northeast': {'lat': 43.04407168029149, 'lng': -76.13916181970849}, 'southwest': {'lat': 43.0413737197085, 'lng': -76.1418597802915}}}   
16        {'location': {'lat': 43.0488189, 'lng': -76.15585519999999}, 'viewport': {'northeast': {'lat': 43.0501197802915, 'lng': -76.15460046970848}, 'southwest': {'lat': 43.0474218197085, 'lng': -76.15729843029149}}}   
17                {'location': {'lat': 43.0501537, 'lng': -76.1543555}, 'viewport': {'northeast': {'lat': 43.0512385302915, 'lng': -76.15323966970848}, 'southwest': {'lat': 43.0485405697085, 'lng': -76.155937630291

## Challenge 4

Notice the nested JSON. Yuk. This can be fixed using `pd.json_normalize` instead of `pd.DataFrame`.

Fix the results above so that the nested JSON is flattened in the dataframe.


In [26]:
df = pd.json_normalize(data)
df.columns

Index(['icon', 'icon_background_color', 'icon_mask_base_uri', 'name', 'photos',
       'place_id', 'reference', 'scope', 'types', 'vicinity',
       'geometry.location.lat', 'geometry.location.lng',
       'geometry.viewport.northeast.lat', 'geometry.viewport.northeast.lng',
       'geometry.viewport.southwest.lat', 'geometry.viewport.southwest.lng',
       'business_status', 'rating', 'user_ratings_total',
       'opening_hours.open_now', 'plus_code.compound_code',
       'plus_code.global_code', 'price_level', 'permanently_closed'],
      dtype='object')

## Challenge 5

Convert your dataframe back into a list of dict.

1. use `to_records()` to convert the dataframe in Challenge 4 back into a `list` of `dict`.
2. loop over the rows and print the bar name, rating, and whether it is open now, 
   for only those rows where the bar is open now.

NOTE: The keys match he columns in the data frame.



In [27]:
for row in df.to_records():
    print(row['name'])

Syracuse
Crowne Plaza Syracuse
The Parkview Hotel
Jefferson Clinton Suites
Courtyard by Marriott Syracuse Downtown at Armory Square
Quality Inn & Suites Downtown
Dinosaur Bar-B-Que
Collegian Hotel & Suites, Trademark Collection by Wyndham
Syracuse Crunch Hockey Club
Mulroy Civic Center
Pastabilities
Hotel Skyler Syracuse, Tapestry Collection by Hilton
US Social Security Administration
Landmark Theatre
Robert V Hingre, MD
Dr. James W. Holsapple, MD
Residence Inn by Marriott Syracuse Downtown at Armory Square
United States Government: U.S. Attorney's Office
Ran D Anbar, MD
Eastside
